### ISSUE TITLE
Some qualifying matches in 2015

### ISSUE THREAD

**Issue by bry17may** [Tennismylife/TML-Database#15]
There are 72 matches from qualies in 2015 from this tournaments, easily identified with Q3 in the round

Stuttgart
s-Hertogenbosch
Nottingham
Newport
Bastad
Umag
Bogota
Gstaad
Atlanta
Kitzbuhel
Winston-Salem
Metz
St. Petersburg
Kuala Lumpur
Shenzhen
Stockholm
Moscow
Valencia

**Comment by Tennismylife** [comment]
Done
