### ISSUE TITLE
Player IDs

### ISSUE THREAD

**Issue by Rnson14** [Tennismylife/TML-Database#32]
Hi, do you have a mapping of the ATP player IDs to those in Jeff Sackmann's original database?

**Comment by Tennismylife** [comment]
Hi,

Nope. I use the only the original ATP IDs. There is no connection with
Sackmann database IDs....and my database is better 😀 (Otherwise I would
not have created mine database using the Tennisbstract one)

Il giorno mar 28 set 2021 alle ore 00:55 Rnson14 ***@***.***>
ha scritto:

**Comment by Rnson14** [comment]
Ok thanks. I managed to scrape them from tennisabstract.com.
